### ISSUE TITLE
Please add search and match support

### ISSUE THREAD

**Issue by irvanherz** [ropensci/rfishbase#106]
Please add support to find partial word in field.
This gv me result,
https://fishbase.ropensci.org/comnames?ComName=Mujair
But this is not
https://fishbase.ropensci.org/comnames?ComName=jair

How about to make like this?
https://fishbase.ropensci.org/comnames?ComName=jair?match=contains

**Comment by cboettig** [comment]
@irvanherz Thanks for the suggestion. @sckott This would be better implemented on the [fishbaseapi](https://github.com/ropensci/fishbaseapi) side, right?

**Comment by sckott** [comment]
yes, if possible. we can do basic searching with just SQL by doing e.g., a `LIKE` query. indexing with Solr would be more powerful, but not sure we want to go there

**Comment by sckott** [comment]
See https://github.com/ropensci/fishbaseapi/issues/59 in the `fishbaseapi` repo - we've already discussed this a bit. We do have the ability to search for fields, since there are so many with the `/listfields` route, but that doesn't address the question here. 

I've only consumed data from Solr, not actually used Solr to index data, but I might try

**Comment by cboettig** [comment]
the latest version returns full tables when given no arguments, e.g. 

```
 com <- rfishbase::common_names()
com
```

users can than subset / fuzzy match as they would any table in R.
