### ISSUE TITLE
Taxonomy data pull from rfishbase and sealifebase

### ISSUE THREAD

**Issue by CharmaneAshbrook** [ropensci/rfishbase#113]
I am trying to pull the entire species data from rfishbase. I successfully pulled the 33,104 records from species_list, but have not been successful with species_names, common_names, synonyms, and sealifebase. My code for species_list is below. Do I need to do something different for these other data frames? --I am doing this because the group I work with regularly uses FAO and RAM Legacy data, as well as NMFS and AFS data. The goal is to create, for every RAM and FAO scientific name, a list of what the scientific name, English name, common name, and synonyms will be for FAO, AFS, NMFS, rfsihbase, and sealifebase. The FAO dataset is about 12701 species and the RAM dataset has 313 species.

species_list()
taxaSL <- species_list()
mode(taxaSL)
taxaSL.df <- data.frame(taxaSL)
write.table(taxaSL.df, file="taxaSL.csv", quote=FALSE, row.names = FALSE, col.names = FALSE)

I'll appreciate any help you can provide.

**Comment by cboettig** [comment]
Good question.  You probably want to use the `load_taxa()` function instead of species list; this will give a data.frame with more information than just species names, e.g.

```r
fishbase <- load_taxa()
```

For sealifebase, you need to specify the URL (needs to be `https`, not `http` like it says in the documentation for `load_taxa()`, @sckott can you push a quick fix to the docs there?)

```r
sealife <- load_taxa(server = "https://fishbase.ropensci.org/sealifebase")
```

(Do you really want all the sealife species in your combined table?  I think it's largely inverts that aren't in RAM or FAO etc, but maybe I'm missing something. )

Also note the above commands load cached data; you should really add the option `update=TRUE` to both commands, e.g. 

```r
fish <- load_taxa(update = TRUE, limit = 120000)
sealife <- load_taxa(server = "https://fishbase.ropensci.org/sealifebase", update = TRUE, limit = 120000)
```

to get all the species currently in the databases.  This will of course take a lot longer.

**Comment by sckott** [comment]
sure, can do

**Comment by CharmaneAshbrook** [comment]
Thanks much. I’ll give it a try!

**Comment by CharmaneAshbrook** [comment]
Thank you!
