### ISSUE TITLE
Genetics?

### ISSUE THREAD

**Issue by szhan** [ropensci/rfishbase#122]
Hi, I am trying to access the fields in the Genetics pages. I do not see support for it at the moment. Is there a way to write a function for it? Please let me know. Thanks!

**Comment by sckott** [comment]
hi @szhan sorry about the delay

can you point to an example page and example data you want? 

there is a genetics table, so we may be able to expose that

**Comment by szhan** [comment]
Hi @sckott !

No problem. Thank you for your reply.

This is an example:
http://www.fishbase.org/Genetics/FishGeneticsList.php?ID=243&GenusName=Oncorhynchus&SpeciesName=nerka

That page provides locality, country, chromosome number, and genetic marker.

**Comment by sckott** [comment]
@szhan try again after reinstalling `devtools::install_github("ropensci/rfishbase")` - see `?genetics`

**Comment by szhan** [comment]
@sckott Thanks! It works. BTW, is there a description of the data fields somewhere (although most are pretty self-explanatory)? It seems that there are more fields than displayed in the FishBase website.

**Comment by sckott** [comment]
No, we don't have any explanation of the data fields. 

@cboettig did we ever get a sense from Fishbase folks if they have explanations of fields in each sql table?

**Comment by cboettig** [comment]
Not really. There's http://www.fishbase.org/manual/contents.htm , which is a somewhat loose description of some of the tables, but not a precise documentation of individuals fields (and not always up-to-date to match those tables either).  

We attempted wrapping some of this information into our `docs` endpoint for each table, e.g. https://fishbase.ropensci.org/docs/genetics/ and https://fishbase.ropensci.org/docs/ , but hasn't been completed.

**Comment by Dengaloo** [comment]
Hi all
I think you will not need to use all data fields because some of those are for internal use only. So better ask us which fields you are interested in and why.
Thanks
Deng

Sent from my iPad

On Jun 19, 2017, at 10:39, Carl Boettiger <notifications@github.com> wrote:

Not really. There's http://www.fishbase.org/manual/contents.htm , which is a somewhat loose description of some of the tables, but not a precise documentation of individuals fields (and not always up-to-date to match those tables either).

We attempted wrapping some of this information into our docs endpoint for each table, e.g. https://fishbase.ropensci.org/docs/genetics/ and https://fishbase.ropensci.org/docs/ , but hasn't been completed.

**Comment by cboettig** [comment]
Looks like the title issue was closed by 4003c95
