### ISSUE TITLE
Novice question regarding usage of validate.names and species functions

### ISSUE THREAD

**Issue by playmobilmeister** [ropensci/rfishbase#137]
Hi, I'm new to R, programming, FB and this package and would appreciate your help with interpreting initial results. Any help with achieving my data cleaning / editing goals will also be much appreciated.

I'm trying to understand results from both validate.names and species functions. I have tried to read the warnings with warnings() with only moderate success.
I have a list of **343** unique Fish sci. names from my raw observations. Right now,  as a result of running the two functions, i have doubts about ~10% of these species, which is significant for my case (looking at alpha diversities stability in diversity time series) so i don't want to move forward with the actual analysis yet.

I would like to:

- validate that species don't appear twice with different names or due to spelling mistakes, and if they do, I would like to then transform all synonymns / spelling mistakes for  one species to one name, so that i can later summarise their abundances. I couldn't find a function for doing exactly that and i guess i should construct it myself.

- validate that all records are indeed Fish (i succeeded with this one by retreiving order for all fish, but only for the **309** species from the species functions (see below)

when i run 'species':
I get the species table with 309 species. 2 species are not recognized, which is fine for my purposes.

when i run validate.names:
There are only **323** validated names in the v.species.names chr vector compared with 342 in the unique species vector.

code and console output:
#Species check against fishbase
> 
> fb.species<-species(u.species, fields = species_fields$id) #see problems. I'm not sure what is the difference between this and the former check
Warning messages:
1: In parse_name(x) : NAs introduced by coercion
2: In parse_name(x) : Species  Blennie could not be parsed
3: In parse_name(x) : NAs introduced by coercion
4: In parse_name(x) : Species  RIEN could not be parsed
5: In species(u.species, fields = species_fields$id) :
  2 of the supplied species names did not match any species in the database: 
Blennie
RIEN
> 
> #Validating Names
> 
> v.species.names<-validate_names(u.species)
There were 50 or more warnings (use warnings() to see the first 50)
> w<-warnings(validate_names(u.species))
There were 50 or more warnings (use warnings() to see the first 50)
> w
Warning messages:
1: In taxendpt(query = list(Genus = genus, Species = species),  ... :
  No species list supplied: retrieving data up to limit......
2: In check_and_parse(resp) : Bad Request (HTTP 400). Anampses meleagrides Centropyge flavissima 
Chaetodon lunula Chaetodon lunulatus Chaetodon reticulatus Chaetodon unimaculatus Chlorurus sordidus....
Ctenochaetus striatus Forcipiger longirostris Halichoeres hortulanus
3: no results found for query https://fishbase.ropensci.org/taxa?SpecCode=&limit=200&Genus=Anampses&Species=Centropyge 
Anampses meleagrides Centropyge flavissima Chaetodon lunula Chaetodon lunulatus Chaetodon reticulatus.......

I pasted only the beginnings of the first 3 warnings due to the length. there are several types. most curious to me is number 3, which did not appear as one of the 2 species that were reportedly not found when running 'species'.

The following file contains the .rdata and a fuller version of my script

[Alpha Diversity community autoregulation.zip](https://github.com/ropensci/rfishbase/files/2067383/Alpha.Diversity.community.autoregulation.zip)

<details> <summary><strong>Session Info</strong></summary>
Session info ----------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, mingw32             
 ui       RStudio (1.1.453)           
 language (EN)                        
 collate  Hebrew_Israel.1255          
 tz       Asia/Jerusalem              
 date     2018-06-04                  

Packages --------------------------------------------------------------------
 package    * version date       source        
 assertthat   0.2.0   2017-04-11 CRAN (R 3.4.2)
 base       * 3.4.2   2017-09-28 local         
 bindr        0.1.1   2018-03-13 CRAN (R 3.4.4)
 bindrcpp     0.2.2   2018-03-29 CRAN (R 3.4.4)
 compiler     3.4.2   2017-09-28 local         
 datasets   * 3.4.2   2017-09-28 local         
 devtools     1.13.5  2018-02-18 CRAN (R 3.4.3)
 digest       0.6.15  2018-01-28 CRAN (R 3.4.3)
 dplyr        0.7.5   2018-05-19 CRAN (R 3.4.4)
 glue         1.2.0   2017-10-29 CRAN (R 3.4.2)
 graphics   * 3.4.2   2017-09-28 local         
 grDevices  * 3.4.2   2017-09-28 local         
 httr         1.3.1   2017-08-20 CRAN (R 3.4.2)
 lazyeval     0.2.1   2017-10-29 CRAN (R 3.4.3)
 magrittr     1.5     2014-11-22 CRAN (R 3.4.2)
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.4)
 methods    * 3.4.2   2017-09-28 local         
 pillar       1.2.3   2018-05-25 CRAN (R 3.4.2)
 pkgconfig    2.0.1   2017-03-21 CRAN (R 3.4.2)
 purrr        0.2.4   2017-10-18 CRAN (R 3.4.2)
 R6           2.2.2   2017-06-17 CRAN (R 3.4.2)
 Rcpp         0.12.17 2018-05-18 CRAN (R 3.4.4)
 rfishbase    2.1.2.4 2018-06-03 local         
 rlang        0.2.0   2018-02-20 CRAN (R 3.4.4)
 stats      * 3.4.2   2017-09-28 local         
 tibble       1.4.2   2018-01-22 CRAN (R 3.4.4)
 tidyr        0.8.1   2018-05-18 CRAN (R 3.4.4)
 tidyselect   0.2.4   2018-02-26 CRAN (R 3.4.4)
 tools        3.4.2   2017-09-28 local         
 utils      * 3.4.2   2017-09-28 local         
 withr        2.1.2   2018-03-15 CRAN (R 3.4.4)
 yaml         2.1.19  2018-05-01 CRAN (R 3.4.4)
```r

```
</details>

**Comment by cboettig** [comment]
@playmobilmeister Thanks for the careful write-up of the issue! (Not all novices give us this nice detail so you're off to a great start!) From a quick look over I think there could be several issues at play here.  

- First, just to be clear, the original list of 343 scientific names came from elsewhere in your research and not fishbase, correct?  This can be at least one source of the variation -- as you're no doubt aware, not all authorities agree on the same classification; so a "scientific name" can be a remarkably ambiguous notion.  From a biodiversity informatics perspective, we prefer to work with species *identifiers* instead, such as `FB:69` (for fishbase species code `69`) or  `ITIS:164712`, to refer to a different authority ([ITIS](https://www.itis.gov)).  This mostly punts rather than answers the question of species name ambiguities, but is good to be aware of.  If you can get valid FishBase species codes for all of your species, that's often more robust to use in your queries (e.g. `species(69)` than the scientific name (`species("Gadus morhua")`).  

- Do some species in your list have 3 part species names?  I believe `rfishbase` is just trying to split all scientific names on a space in order to resolve the fishbase species codes automatically when you use a species names list.  You might have better luck querying for matching Species and Genus directly rather than letting the function try and parse the scientific name.  This will impact both `validate_names()` and `species()` function calls. 

Missing rows in you your returns basically mean that the species are not being matched in fishbase.  validate_names is supposed to help with this by providing some fuzzy matches, as you see in your example, you get more matches back from that but not all.  This could indicate that the names still missing from validate_names return have spelling errors, character encoding errors, don't conform to FB taxonomy, aren't in fishbase, or are just failing to match for a reason we haven't dug out yet.  Working with names is hard stuff!

**Comment by playmobilmeister** [comment]
thanks for the tips !
That's correct, the 343  sci. names came from another research, not from FB. 
I will try to get FB codes, but i don't think i will get one.

 investigating the unique names vector more closely, i found out: 

- there is indeed a number of observations recognized only to the Genus level ("sp" is the second word)

-  2 observations have actually 4 words, but none have 3. those 2 observations are also identified to the species level, but the text has additional remarks

I take it then that what you would do is to consider all other cases manually. That is, to search them in FB and decide one by one how to define them ?

**Comment by cboettig** [comment]
@playmobilmeister Yes!  

- For the 323 rows you are getting back from the `validate_names`, you should be all set, since that function should give you the names that fishbase knows.  So it's just the remaining 20 names you'll need to clean up more manually.  Searching for them on FB website is probably the best way to start.
