### ISSUE TITLE
Diet Function Does Not Return Diet Items or Diet Quantities

### ISSUE THREAD

**Issue by sborstein** [ropensci/rfishbase#155]
I have recently used rfishbase 3.0 for the first time (have used previous versions extensively). I have noticed in the new version that the diet function does not return the prey items consumed nor their dietary contribution as it did in previous versions (ran using `DietDat<-diet("Pomacanthus paru")`). It appears the dimensions of the returned object are substantially smaller in the current version as opposed to previous versions (41 columns in the present vs 53 in 2.1). Specifically, it appears that the current version does not return the `FoodI`, `FoodII`, `FoodIII`, or `Stage` columns describing the prey item or the `DietPercent` containing the percentage consumed. For me, and I would guess most others who want to use the function as well, this is the most useful information that the function could provide. Is there a way to make this information accessible in the current version of rfishbase?

Thanks,
Sam

**Comment by cboettig** [comment]
Apologies for the slow reply, this got buried in my inbox.

I think you may be looking for the `fooditems()`  function?  Recall that you can always use the `list_fields` function to help discover which table has the columns of interest:

```
list_fields("FoodII")
# A tibble: 3 x 1
  table     
  <chr>     
1 diet_items
2 fooditems 
3 ration    
> 
```

HTH!  Please re-open this issue if this doesn't resolve things.

**Comment by watrbeans** [comment]
Hi Sam,

I wonder if you were able to resolve this concern on the dimensions of the diet function? I'm trying to replicate the methodology used by [Borstein et al in 2018](url), which involves a custom function using the diet table. However, the custom function requires that the length of columns in the diet table be 53. Adapting the function to run anyway is tricky, since the diet function returns columns with a length of 41 now, and I don't know what all of the columns might be in the old version to successfully recreate it. 

I tried to use older releases of fishbase (specifically "19.04" and "21.06") but don't seem to be getting different results when running diet. 

Any thoughts or alternative solutions to the problem greatly appreciated!
