### ISSUE TITLE
Species table in rfishbase package

### ISSUE THREAD

**Issue by ceri-w** [ropensci/rfishbase#221]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by ceri-w** [comment]
Hello, 
I have just reinstalled the rfishbase package in R and the species table has gone from 34299 species to 13355, do you know why this is?

Thanks, 
Ceri

**Comment by cboettig** [comment]
@ceri-w yikes, thanks for reporting, that can't possible be right.  Can you provide a [reprex](https://reprex.tidyverse.org/)?

Note that you can request the version of the data you want, so you can opt for the old or new version like so:


``` r
library(rfishbase)
library(dplyr)

# previous data release, "19.04"
species(version="19.04") %>% nrow()
#> [1] 34299


# latest data release, "21.04"
species() %>% nrow()  # yikes! too many.  
#> [1] 61603

# but sensible number of unique SpecCode at least
species() %>% select(SpecCode) %>% distinct() %>% nrow()
#> [1] 35148
```

<sup>Created on 2021-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


So I'm seeing too many, not too few entries, which look like like a file parsing problem to me.  lemme know what you see. Sounds like your import or download may have been interrupted.  we can see if we can detect that in future versions to avoid that issue.

**Comment by ceri-w** [comment]
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(rfishbase)

species <- species(species_list())
species() %>% nrow() 
#> [1] 22891
#> [1] 22891
```

<sup>Created on 2021-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cboettig** [comment]
hmm, 22,891.  weird!  Try this:

```r
fs::dir_delete(rfishbase:::db_dir())
rfishbase::species(version="21.04") %>% nrow()
```


This will force a delete of your fishbase cache, making fishbase re-download and re-import the data, so it will be slow but give us a clean slate.

**Comment by ceri-w** [comment]
seems to still come up with the same number unfortunately
``` r
library(dbplyr)
library(rfishbase)

fs::dir_delete(rfishbase:::db_dir())
rfishbase::species(version="21.04") %>% nrow()
#> Importing /Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/species_fb_2104.tsv.bz2 in 1000000 line chunks:
#>  ...Done! (in 7.960645 secs)
#> Importing /Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/genera_fb_2104.tsv.bz2 in 1000000 line chunks:
#>  ...Done! (in 0.740694 secs)
#> Importing /Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/families_fb_2104.tsv.bz2 in 1000000 line chunks:
#>  ...Done! (in 4.339938 secs)
#> Importing /Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/orders_fb_2104.tsv.bz2 in 1000000 line chunks:
#>  ...Done! (in 2.723283 secs)
#> Importing /Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/classes_fb_2104.tsv.bz2 in 1000000 line chunks:
#>  ...Done! (in 0.9767599 secs)
#> Joining, by = c("Subfamily", "GenCode", "FamCode")
#> Joining, by = "FamCode"
#> Joining, by = c("Order", "Ordnum", "Class", "ClassNum")
#> Joining, by = c("Class", "ClassNum")
#> [1] 22891
```

<sup>Created on 2021-08-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cboettig** [comment]
Sorry, bad instructions.  after running  `fs::dir_delete(rfishbase:::db_dir())`, you also need to restart the R session.  Otherwise the data is still in cache.  

Another thing to check, try:

```r
readr::read_tsv(file.path(rfishbase:::db_dir(), "species_fb_2104.tsv.bz2")) %>% nrow()
```

This is the "true" species table, before it gets joined to the higher-taxa tables you see in the messages above.  it should have 35,330 rows.

**Comment by ceri-w** [comment]
I'm still getting 22,891 sp when I try this and when I try the "true" species table I get 13116 sp
``` r
library("rfishbase")
library("dbplyr")
library("reprex")
readr::read_tsv(file.path(rfishbase:::db_dir(), "species_fb_2104.tsv.bz2")) %>% nrow()
#> 
#> ── Column specification ────────────────────────────────────────────────────────
#> cols(
#>   .default = col_double(),
#>   SpecCode = col_character(),
#>   Genus = col_character(),
#>   Species = col_character(),
#>   Author = col_character(),
#>   FBname = col_character(),
#>   PicPreferredName = col_character(),
#>   PicPreferredNameM = col_character(),
#>   PicPreferredNameF = col_character(),
#>   PicPreferredNameJ = col_character(),
#>   Subfamily = col_character(),
#>   BodyShapeI = col_character(),
#>   Source = col_character(),
#>   AuthorRef = col_logical(),
#>   Remark = col_character(),
#>   DemersPelag = col_character(),
#>   Amphibious = col_logical(),
#>   AmphibiousRef = col_logical(),
#>   AnaCat = col_character(),
#>   LTypeMaxM = col_character(),
#>   LTypeMaxF = col_character()
#>   # ... with 28 more columns
#> )
#> ℹ Use `spec()` for the full column specifications.
#> Warning: 553 parsing failures.
#>  row col    expected     actual                                                                                                 file
#>  374  -- 101 columns 91 columns '/Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/species_fb_2104.tsv.bz2'
#>  375  -- 101 columns 11 columns '/Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/species_fb_2104.tsv.bz2'
#>  826  -- 101 columns 91 columns '/Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/species_fb_2104.tsv.bz2'
#>  827  -- 101 columns 11 columns '/Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/species_fb_2104.tsv.bz2'
#> 1162  -- 101 columns 91 columns '/Users/ceriwebster/Library/Application Support/org.R-project.R/R/rfishbase/species_fb_2104.tsv.bz2'
#> .... ... ........... .......... ....................................................................................................
#> See problems(...) for more details.
#> [1] 13116


```

<sup>Created on 2021-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ReneevanDorst** [comment]
I am having the exact same problem, and the suggested fixes don't work for me either. All species after "Girella feliciana" seem to have disappeared (alphabetical order).

Cheers,
Renee

**Comment by cboettig** [comment]
Thanks all for reporting, your tests are very helpful in tracking this down.  So far I am still unable to reproduce this behavior, though it sounds like we have now isolated it to the raw data file.  Perhaps your local download terminated early?  Please try this reprex and lemme know if you're seeing either a different digest or different number of rows.  Thanks much!!

``` r
download.file("https://github.com/ropensci/rfishbase/releases/download/fb-21.04/fb.2fspecies.tsv.bz2", 
              "species_fb_2104.tsv.bz2")
digest::digest("species_fb_2104.tsv.bz2", algo = "sha256", file=TRUE)
#> [1] "453d9f2ac8e613f5ee5c8e79c1e14ba55103f6c5142539fb23a6176be91d10c4"

df <- readr::read_tsv("species_fb_2104.tsv.bz2") 
#> Warning: One or more parsing issues, see `problems()` for details
#> Rows: 35330 Columns: 101
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: "\t"
#> chr  (38): SpecCode, Genus, Species, Author, FBname, PicPreferredName, PicPr...
#> dbl  (53): SpeciesRefNo, FamCode, GenCode, SubGenCode, TaxIssue, Fresh, Brac...
#> lgl   (7): AuthorRef, Amphibious, AmphibiousRef, EggPic, Complete, Profile, TS
#> dttm  (3): DateEntered, DateModified, DateChecked
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
nrow(df)
#> [1] 35330
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ReneevanDorst** [comment]
When running this, I still have the same problem, only 13116 rows..
I get the same digest, and then the same output ceri-w had above, with 13116 rows instead of 35330.

**Comment by cboettig** [comment]
@ReneevanDorst wow that is a puzzle!  Can you give me the output of `sessionInfo()`

Can you also try reading in the same file with, say, `read.table()`?  

Since the digest matches, the file is not being truncated by a premature download or anything.  So I'm really surprised to see it reading in 13116 rows.  At this point we are not touching any `rfishbase` code, this is simply a matter of us reading apparently the same .tsv file and getting different results!  very strange....

**Comment by ReneevanDorst** [comment]
Very strange!

This is the output I get from sessionInfo: (see further below what happens when I use read.table)

sessionInfo()
#> R version 4.0.5 (2021-03-31)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19043)
#>
#> Matrix products: default
#> 
#> locale:
#>[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
#> [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] rfishbase_3.1.9 tidyr_1.1.3     dplyr_1.0.6     ggplot2_3.3.4  
#> 
#> loaded via a namespace (and not attached):
#>  [1] dbplyr_2.0.0      pillar_1.6.1      compiler_4.0.5    prettyunits_1.1.1
#>  [5] progress_1.2.2    tools_4.0.5       digest_0.6.27     memoise_1.1.0    
#>  [9] jsonlite_1.7.2    evaluate_0.14     lifecycle_1.0.0   tibble_3.1.2     
#> [13] gtable_0.3.0      pkgconfig_2.0.3   rlang_0.4.11      rstudioapi_0.13  
#> [17] cli_2.5.0         DBI_1.1.1         curl_4.3.1        yaml_2.2.1       
#> [21] xfun_0.19         httr_1.4.2        arkdb_0.0.12      withr_2.4.2      
#> [25] stringr_1.4.0     knitr_1.30        hms_1.1.0         generics_0.1.0   
#> [29] vctrs_0.3.8       grid_4.0.5        tidyselect_1.1.1  glue_1.4.2       
#> [33] R6_2.5.0          gh_1.1.0          fansi_0.5.0       rmarkdown_2.5    
#> [37] readr_1.4.0       purrr_0.3.4       magrittr_2.0.1    scales_1.1.1     
#> [41] ellipsis_0.3.2    htmltools_0.5.1.1 assertthat_0.2.1  colorspace_2.0-1 
#> [45] utf8_1.2.1        stringi_1.6.2     munsell_0.5.0     crayon_1.4.1




When I use `df2 <- read.table(file = "species_fb_2104.tsv.bz2",sep = '\t', header = TRUE, fill=TRUE)` to read in the file I actually get more rows: 17863. And there is species up to "Zungaropsis" included in the file. However, still many species (like one of my study species "Perca fluviatilis"), are missing from the table.

I also noticed that in the file with 13116 rows, there are some other things going wrong. In multiple places (e.g. row 12992-13033) what is in the cell doesn't match up with the rest of the column (e.g. there is some description of references in the spec code column). So not each row is actually a species.

**Comment by cboettig** [comment]
@ReneevanDorst Thank you, this is very helpful!!   Very much sounds like a parsing issue.  

Please try upgrading your version of `readr` to the latest release (2.0.1) and try again and see if that fixes things?

@ceri-w Could you also confirm your version of `readr` and try upgrading if it is not the most recent version?

**Comment by ReneevanDorst** [comment]
Hi @cboettig, thanks for all the help! So I have updated readr now to the 2.0.1 version. Now I do get the right amount of rows when I use your code (df <- readr::read_tsv("species_fb_2104.tsv.bz2") , but when I use my own code and just call the rfishbase function `ecology` or `species`, still all the species after "Girella feliciana" are missing .. So my issue is still not fixed unfortunately. 

Then I looked back here, and tried to use `species(version="19.04")` instead of just `species()`, and then it does actually work (34299 rows). So it seems with the updated readr the old rfishbase version works again for me (it didn't before when I tried), but the latest rfishbase version does not work..

**Comment by ceri-w** [comment]
Yep my readr was out of date, I've updated it, now everything is back to normal, thanks so much for your help!

**Comment by cboettig** [comment]
@ReneevanDorst thanks and sorry for the trouble.  You'll probably need to purge the local database as well, since these files are imported into the SQLite, which was populated by the old buggy version of `readr`.  Please try:

```r
fs::dir_delete(rfishbase:::db_dir())
rfishbase::species(version="21.04") %>% nrow()
```

as noted above.

**Comment by ReneevanDorst** [comment]
That did the trick, everything is working again! Thanks for all the help!

**Comment by jaseeverett** [comment]
@cboettig I am not sure if this is related but I am getting replicates back from `species()`. For example:
```
rfishbase::species("Heterodontus portusjacksoni") %>% nrow()
[1] 2

# but distinct shows the rows are identical.
rfishbase::species("Heterodontus portusjacksoni") %>% distinct() %>% nrow()
[1] 1
```

Like you at the top of this thread, I get
```
# latest data release, "21.04"
species() %>% nrow()
#> [1] 61603

# but sensible number of unique SpecCode at least
species() %>% select(SpecCode) %>% distinct() %>% nrow()
#> [1] 35148
```

I have deleted the species database using `fs::dir_delete(rfishbase:::db_dir())` and I still get the same result. Are these dupes expected? Should I be getting 61603 rows for the species database?

**Comment by cboettig** [comment]
@jaseeverett Thanks for the report, yup, obviously a bug somewhere.  

Looks like this is mostly due to to duplicated rows, so just calling `distinct()` goes a long way to cleaning things up: 

```r
 rfishbase::species() %>% distinct() 
# A tibble: 35,156 × 101
````

There's a few (8 rows) where the SpecCode is duplicated, but closer inspection it looks like those 8 rows are just parsing errors, th spec code repeated is just `NA` or such.  Will have to see where upstream the duplication occurred and filter them out, meanwhile, a call to `distinct()` should resolve the duplication.

**Comment by ceri-w** [comment]
I also have the same problem as @jaseeverett with duplicates of species but also some of the species being listed as "0-1" - it's not a huge problem since I just call distinct() and remove the numerical ones - but just thought I would give you a heads up
