### ISSUE TITLE
release fb-21.06 not showing with available_releases() [v. 3.1.9.99]

### ISSUE THREAD

**Issue by MichaelJSchram** [ropensci/rfishbase#232]
I saw that fb-21.06 was released a couple of days ago, but it's not showing up as a result when running available_releases(). 

Will it require a package update for fb-21.06 to be accessible, or is it already in place but not showing up for some reason?

Thanks!

**Comment by cboettig** [comment]
Sharp eyes, that's still work in progress; needs a bit of testing.  

No package update should be needed; but `rfishbase` won't switch to the 21.06 data until we edit this file on GitHub: https://raw.githubusercontent.com/ropensci/rfishbase/master/inst/extdata/rfishbase_available_releases.txt

(This way, we can make a release to store the new data on GitHub and test that things work before users start getting that data!  Also avoids the GitHub API, which can create issues due to rate-limiting)
