### ISSUE TITLE
getSize function not working

### ISSUE THREAD

**Issue by mpaulasg** [ropensci/rfishbase#242]
I'm trying to use the getSize function but it's not working. I've used the example from the package:

data(fishbase) 
yr <-getSize(fish.data, "age") 
hist(yr, breaks=40, main="Age Distribution", xlab="age (years)"); 
nfish <-length(fish.data)

Warning message:
In data(fishbase) : data set ‘fishbase’ not found

I have tried with my own data, and I receive this error:
Error in getSize(for_K, "length") : could not find function "getSize"

Any help will be appreciated, thanks!

Paula

**Comment by cboettig** [comment]
As noted in the [README](https://github.com/ropensci/rfishbase#readme), the package has gone though several iterations and functions from the original paper have since been replaced with more extensive data access methods.  For instance, if you want to compare average length of a species and longevity:

```
library(dplyr)
rfishbase::species() %>% select("Species", "Length", "LongevityWild")
```

If you want length weight relationships of individiual specimens of a species, you might rather look at the length_weight table:

```
library(dplyr)
rfishbase::length_weight()
```

and so forth.  Please see the README for an overview of current package functionality.  Hope this helps!
