### ISSUE TITLE
Working with dowloaded tables offline

### ISSUE THREAD

**Issue by juanmayorgahenao** [ropensci/rfishbase#250]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

Hi -  I have a brief clarifying question: After using `fb_import`, are dowloaded tables available for use in fresh R sessions without internet connection? 

Thank you

**Comment by cboettig** [comment]
yes

**Comment by cboettig** [comment]
Thanks for the report.  

The first part,

```
<duckdb_connection 15820 driver=<duckdb_driver c9030 dbdir=':memory:' read_only=FALSE>>
```
is expected.  `rfishbase` uses `duckdb` only to read the static parquet files that `fb_import` has downloaded locally to your computer.  `duckdb` should have no need for an additional on-disk database storage, because it can use parquet as the on-disk database.  

However, after you disconnect from the internet, it seems that for some reason it fails to find the local copy, and so goes looking for the copy on the internet.  We'll have to debug why that is failing for you.  Can you first make sure you have the most recent version of `contentid` and `rfishbase`?

`fb_import` uses the Provenance log to determine the identifier for a particular table.  e.g. here is the entry for the most recent version of the estimate table: https://github.com/ropensci/rfishbase/blob/6ebd80e92a93366ce6b159eadd94c5e47f06d31e/inst/prov/fb.prov#L653-L660

See if you can resolve that id directly offline as well as online:

```
path <- contentid::resolve("hash://sha256/7f258428dadc8031f5e8111ab088d4f3b00130b1985b318153a98d2f7cdf2b66", store=TRUE, dir = rfisbase::db_dir() )
path
```

If this succeeds, you should get  a path back that points to `rfishbase::db_dir()`, with the file named by it's sha hash (and no file extension).  If it is failing offline, then `path` will be `NA`.  Can you try that and let me know?  

Thanks for the help and sorry for the trouble.  

```

**Comment by juanmayorgahenao** [comment]
Thanks @cboettig. This succeeds online with output: 

`"/Users/marinedatascience/Library/Application Support/org.R-project.R/R/rfishbase/sha256/7f/25/7f258428dadc8031f5e8111ab088d4f3b00130b1985b318153a98d2f7cdf2b66"`

but fails offline with error message: 

`Warning: Error in curl::curl_fetch_memory(file, handle): LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60

Warning: Error in curl::curl_fetch_memory(file, handle): LibreSSL SSL_read: error:02FFF03C:system library:func(4095):Operation timed out, errno 60

Warning: Error in curl::curl_fetch_memory(file, handle): Could not resolve host: hash-archive.org

Warning: Error in curl::curl_fetch_memory(file, handle): Could not resolve host: hash-archive.carlboettiger.info

Warning in curl::curl_fetch_memory(url, handle = handle) :
  Could not resolve host: archive.softwareheritage.org
Warning in curl::curl_fetch_memory(url, handle = handle) :
  Could not resolve host: cn.dataone.org
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match`

Thank you for your help!

**Comment by juanmayorgahenao** [comment]
I'm working with the a fresh github install  of both packages

**Comment by cboettig** [comment]
This should be a bit more stable with the latest release, which simplifies some of the logic.  See updated notes in README.  apologies for the trouble earlier!
