### ISSUE TITLE
familySearch Error: could not find function "familySearch"

### ISSUE THREAD

**Issue by megbalk** [ropensci/rfishbase#32]
Hey,

I installed rfishbase from github using devtools under R 3.1.2 using OSX Mavericks. When I run familySearch or habitatSearch I get the following error: Error: could not find function "familySearch". I am using the examples from the tutorial (https://github.com/ropensci/rfishbase/blob/master/inst/doc/rfishbase/rfishbase_github.md). 

My install commands were: 
library(devtools)
install_github("rfishbase", "ropensci")

Then I ran with these:
rm(list=ls())
require(rfishbase)
require(XML)
require(RCurl)

We installed from the CRAN packages as well with the same results.

**Comment by cboettig** [comment]
@megbalk Sorry about that, the `familySearch` function was deprecated in favor of `which_fish` function (see https://github.com/ropensci/rfishbase/blob/master/NEWS#L50), so you could do:

```r
my_fish <- which_fish("Labridae", using="Family")
```

If you prefer, the old function is still available, just hidden.  Add the rfishbase namespace with three `:`'s to access it : 


```r
my_fish <- rfishbase:::familySearch("Labridae")
```

Just a warning that the current `rfishbase` on CRAN (master branch on Github) has issues (mostly due to limitations of interacting with fishbase.org website).  We're getting close to having a new version of `rfishbase` built to interact directly with the fishbase.org backend and it should be both much easier to use and more powerful.  (You'll see the current development on the rfishbase2.0 branch here on Github).  If you're willing to wait a few weeks and test the development version, it might save you a lot of trouble.  We're also open to any feature requests you'd like to see in the new version (either in terms of accessing particular data or just in terms of ease of use).

**Comment by megbalk** [comment]
@cboettig Thank you!

**Comment by cboettig** [comment]
@megbalk we're about ready to move rfishbase2.0 onto master Github branch & deprecate any further development on the original package (it will be a bit longer before we're ready for CRAN).  

In rfishbase2.0, you can now get Family (or other taxonomic units) using the `species_list` function, e.g.

```r
labrids <- species_list(Family="Labridae")
```

which will return a list of species names for all species in the Family (instead of returning that ugly long list of TRUE/FALSE).  You can pass this species list to most of the other functions of rfishbase2.0 to generate a table with rows as species and columns as the relevant characteristics, e.g.

```r
species_info(labrids)
ecology(labrids)
```

Do let us know if anything is unclear or not working; we appreciate any early testing of rfishbase2.0!

**Comment by megbalk** [comment]
@cboettig Great! Looking forward to it!
