### ISSUE TITLE
?morphology and column nams

### ISSUE THREAD

**Issue by fishandfish** [ropensci/rfishbase#35]
Hi @cboettig,
When I type in the following I get this error.

> ?morphology
Warning messages:
1: In fetch(key) : internal error -3 in R_decompress1
2: In strsplit(msg, "\n") : input string 1 is invalid in this locale

Any thoughts? I want to find the Max total length and common length column names.
Thanks,
K

**Comment by cboettig** [comment]
I think you're testing on an older version of rfishbase.  Can you restart R, and then re-install from github?

Unfortunately, I haven't documented all the fields (they aren't documented literally in fishbase itself, so this requires a bit of work -- input much appreciated). So at the moment you're stuck looking at the [FishBase manual](http://www.fishbase.org/manual/english/contents.htm), for example, here's the [chapter on the morphology table](http://www.fishbase.org/manual/english/fishbasethe_morphology_table.htm) to see if it has what you want.  Otherwise you might just make a sample query and see what it gives you.  

Knowing where the information is on Fishbase.org might help.  For instance, if it's on the summary page for the species, chances are you want `species_info()`.  (Maybe we should rename that function `species_summary()`).  

Based on what you're describing, that's where the data you want live, e.g. try:

```r
species_info(common_to_sci("trout"), species_fields$morph)
> species_info(common_to_sci("trout"), species_fields$morph)
```

which gives the table:

```
  Length LTypeMaxM LengthFemale LTypeMaxF CommonLength LTypeComM CommonLengthF
1    140        SL           NA        NA           72        TL            NA
2    120        TL           NA        NA           60        TL            NA
3     86        SL           NA        NA        26.35        TL            NA
4    107        TL           NA        NA           40        TL            NA
5     90        TL           NA        NA           40        TL            NA
6    127        TL           NA        NA         37.5        TL            NA
7    120        SL           NA        NA           35        SL            NA
8     60        TL           NA        NA           NA        NA            NA
9     96        SL           NA        NA           65        FL            NA
Variables not shown: LTypeComF (chr), Weight (dbl), WeightFemale (chr)

```

However, perhaps you want the [popchar table](http://www.fishbase.org/manual/english/fishbasethe_popchar_table.htm) instead.  You see what I'm up against here -- the organization of these tables doesn't make any more sense to me than it does to you.  Once I get my head around the details more, I'm hoping to add some more higher-level functions that have richer, accurate documentation and return what you expect.  But for now it requires some digging.

**Comment by fishandfish** [comment]
Thanks @cboettig!
I will certainly explore this more and let you know any ideas. Is there a way to the species_info(common_to_sci("trout"), species_fields$morph), but for all species in Fishbase? Ultimately, I would like to get all fish lengths for the 30000+ species.
Cheers,K

**Comment by cboettig** [comment]
Sure. `species_list()` is your go-to function to create lists of species names, e.g. you get all 31,454 species of the ray-finned fishes with `x = species_list(Class="Actinopterygii")`.  To get all 32,792 species, just use `x = species_list()` with no arguments.  

Note that running `species_info()` on the complete list will be slow, since we have to query one species at a time.  If you know exactly what fields you want (e.g. say, `c("Length", "LTypeMaxM" "CommonLength", "LTypeComM")`) then it is probably faster if you specify them explicitly, instead of using the `species_fields$morph` list -- as you've probably seen, `species_fields` is just me collecting the different table columns into somewhat more logical subsets..  So you might run something like:


```r
x <- species_list()
df <- species_info(x, fields=c("Length", "LTypeMaxM" "CommonLength", "LTypeComM"))
```

and then go to lunch.

**Comment by fishandfish** [comment]
Thanks, this worked and I was able to extract the length data for all 32792 species.
However, when I tried to extract the trophic level info 

FISHLIST <- species_list()
TLFB<-ecology(FISHLIST,fields=c("SpecCode", "DietTroph", "DietSeTroph")) 

it only included DietTroph and SE data for 10482 species, and it included species with NA. Shouldn't this search have yielded the same amount of species in species_list (32792) and not just a subset?

Appreciate it,
K

**Comment by cboettig** [comment]
@fishandfish Nope, note that the ecology table simply doesn't have entries
for all species.  (This is true for many species for many tables: e.g. If
you're looking at fishbase.org summary pages under "more information",
you'll see links to most common tables. If the species has no entry for the
given table, e.g. for "Ecology", it will be greyed out).

Similarly, just because a species has some entry in the table doesn't mean
it has all fields -- there's loads of missing data in FishBase still. The
ecology() function will return a row for the species as long as the species
has an entry in the Ecology table; even if the values for the fields you
query are all NAs (remember that there are over 100 fields in the Ecology
table, only one needs to not be an NA for the table to exist).

Remember also that R is designed to handle missing data -- few other
languages have 'missing data' baked in as a fundamental data type, but R
does since it's so essential to statistics on real data.  Still, it's left
up to the user to be sure to handle missing data appropriately (e.g.
missing data is almost never just missing at random; rarer fish are much
more likely to have more missing data).  Didn't mean to sound paternal --
you probably know all that -- but just something to keep in mind!

**Comment by fishandfish** [comment]
Hi @cboettig ,
I appreciate the response. Since there are many missing data from FishBase, Do you envision rfishbase having the ability to upload some parameters to Fishbase? For instance if a scientist has csv file with trophic levels for a list of species. This might be a useful addition to rfishbase and help speed up the data acquisition process.
Cheers, K

**Comment by cboettig** [comment]
Great idea, I'll look into that with the FishBase team

**Comment by fishandfish** [comment]
Thanks @cboettig,
Another thing I noticed is the "Estimates of some properties based on models" section. For instance they have a trophic level estimate "Trophic Level (Ref. 69278):  3.5   ±0.6 se; Based on size and trophs of closest relatives" that would be useful to be able to extract. The example above is for Abyssocottus elochini which does not have a DietTrophicLevel or Diet TLse estimate. Do we have a way to access this table?
Cheers, K
PS - Thanks for being so helpful, the world of fisheries scientists are going to thank you for many generations!

**Comment by cboettig** [comment]
Hmm, I see that example on the summary page for the species, but it's not obvious to me how they are computing it (that is, what they have used to define "closest relatives".)  It does not appear to come from one of the other tables.  

Of course you could always come up with a list of closest relatives and produce your own estimate, but  needless to say this wouldn't be appropriate for making certain statistical statements about the trophic levels of some group of fish, since this not independent data; but could be useful if you just needed a parameterization for a particular species.

**Comment by fsoudijn** [comment]
There is some more info about these estimates on the food-items-table page in box 26 (http://www.fishbase.org/manual/English/fishbasethe_food_items_table.htm). When there is no food information available, the trophic level is estimated based on taxnomically related species and the relationship between body size and trophic level. The info is stored in a table called "estimates". I guess it is questionable how good this estimate really is and independece can certainly be problematic , but in some cases it may be the best info that is available.

**Comment by cboettig** [comment]
Thanks.  Those docs suggest that these values are found in a new table
called "estimates", so I can look into adding an `estimates()` function to
access that information.

**Comment by cboettig** [comment]
Moving the request re `estimates` to a new issue for clarity; and closing this resolved issue.
