### ISSUE TITLE
getLengthWeight 

### ISSUE THREAD

**Issue by btmarti25** [ropensci/rfishbase#41]
I am not able to get the getLengthWeight function to work, and not sure if it is a bug, or something I am doing. I have tried it out on a few species, and get similar errors:

> getLengthWeight(fish.data[1])
Error in `$<-.data.frame`(`*tmp*`, "r2", value = numeric(0)) : 
  replacement has 0 rows, data has 25
> getLengthWeight(fish.data[2])
Error in `$<-.data.frame`(`*tmp*`, "r2", value = numeric(0)) : 
  replacement has 0 rows, data has 22
> getLengthWeight(fish.data[3])
Error in `$<-.data.frame`(`*tmp*`, "r2", value = numeric(0)) : 
  replacement has 0 rows, data has 6

**Comment by cboettig** [comment]
@btmarti25 Would you mind installing the version from Github and using the new function `length_weight()` instead of the old function `getLengthWeight`?  I think you'll find the new function easier to use, a bit more robust, and providing more data.  

You don't have to use the cumbersome `fish.data[1]` notation any more, `length_weight()`, and all the new functions, just take a list of species names: 

```r
length_weight("Oreochromis niloticus")
```
and returns a data.frame corresponding to the table shown on the Fishbase.org website, e.g. http://www.fishbase.org/PopDyn/LWRelationshipList.php?ID=2&GenusName=Oreochromis&SpeciesName=niloticus&fc=349.  (The table we return isn't quite as tidy yet -- e.g., we show SpecCode species codes isntead of the species names, and a `C_code` column instead of country names.  But the data is actually more complete).  

If you provide more than one species name, additional names are just added as additional rows in the data.frame; with each species given a unique stock code.  There are also some helper functions that can generate a list of species names given a Genus, Family, or common name; see the README.  

Sorry to change everything on you in this way.  The old version of rfishbase was increasingly facing stability problems due to limitations of web scraping, as you have seen.  The new version uses an independent API backend we have written to provide much more complete and reliable access to data. We're still in testing mode but should have a first release onto CRAN in the near future.  Meanwhile any feedback is appreciated!

**Comment by btmarti25** [comment]
@cboettig Thanks!

The new version is a big improvement!
