### ISSUE TITLE
Trophic info Ecology table imported differently?

### ISSUE THREAD

**Issue by fsoudijn** [ropensci/rfishbase#44]
Great project! Thanks for your effort in developing this package.

When I import info from the ecology table, in my case regarding the fish diet, it seems as if some info is imported differently. Maybe this is the result of the package importing something other than the info that is displayed on the ecology summary page on the fishbase website, but I have not been able to deduce where it comes from exactly.

For example:

sp1<-c("Myxine glutinosa","Anoplopoma fimbria","Ammodytes dubius")
diet<-c("SpecCode","DietTroph","DietSeTroph","DietTLu","DietseTLu","FoodTroph","FoodSeTroph")
ecology(sp1,fields=diet)

gives:
  SpecCode DietTroph DietSeTroph DietTLu DietseTLu FoodTroph FoodSeTroph
1     2513      3.45        0.66    3.40      0.59      4.01        0.70
2      512      3.83        0.61      NA        NA      4.11        0.88
3     3821      3.14        0.22    3.11      0.17      3.27        0.38

The summary of the ecology on the fishbase website, gives the following (varaibles in the same order):
1    2514    4.54    NA    3.40 	0.59    4.01 	0.70  
2    512    3.84 	0.21    NA    NA    4.11 	0.88 
3    3821    3.20 	0.07 	3.11 	0.17     3.27 	0.38 

The "DietTLu" and "FoodTroph" variables match perfectly, but the "DietTroph" info deviates. This is especially obvious for the first species in the example. 

What do you think creates this difference? Thanks so much!
Floor

**Comment by cboettig** [comment]
Thanks for reporting this issue.  rfishbase is still using a somewhat older
version of the fishbase database that was provided for developing and
testing purposes.  I've written to the fishbase team to see if we can get
the updated database to provide until their team is ready to serve our API
directly.  I suspect that this is the reason for the differences, but
cannot be sure.

Note that in the first row in your example, the species actually has a
different SpecCode than the one rfishbase is using; so it is possible the
taxonomy has shifted since and you are not getting the species you think
you are getting.  Check out the Synonyms table for this species to see if
has more information.

**Comment by fsoudijn** [comment]
Thanks for your response!

I am afraid the difference in speccode for the first species was a typo I made, 2514 should be 2513.

**Comment by cboettig** [comment]
okay thanks. waiting to hear back from the fishbase team about the
possibility of updates to the database.

**Comment by cboettig** [comment]
I've updated the API to serve a more recent version of the database (dated May 26).  Hopefully this resolves the discrepancies you noted between particularly data in rfishbase and on fishbase.org. let me know if the issue persists!

**Comment by fsoudijn** [comment]
Great! Thank you. I will have a look at it and let you know.

**Comment by fsoudijn** [comment]
Yes, I think that fixed it! Thanks a lot.
