### ISSUE TITLE
Min/Max temp?

### ISSUE THREAD

**Issue by jafflerbach** [ropensci/rfishbase#47]
In rfishbase 2.0, is there a function to extract the min and max temperatures per species? This info is found under **Environment / Climate / Range** section on [fishbase](http://www.fishbase.org/summary/Clupea-harengus.html) - similar to requests in issue #19. In the previous version, getEnviroClimateRange() spit it out along with range info but I'm not seeing the same functionality in either species(), ecology() or distribution(). Not sure if I'm missing something but it would be nice to have min/max and preferred min/max temps if available per species (similar to how Depth is provided)

**Comment by cboettig** [comment]
Good question; I wish fishbase had a more obvious organization to the
database backend but unfortunately that's not the case.  Maybe there are
things we can do in the r package to help.

I think what you're looking for is under the "Comments" field from the
species table, e.g. `species(species_list, fields="Comments")`.
Unfortunately, it's in plain text there, so you (or I) would need to regex
out the numbers.  and given that the field is called "Comments", who knows
how many of the species have temperature ranges in that area.  (As you've
seen, Depth range is also in this species table, but as a proper field.

**Comment by jafflerbach** [comment]
I do find it a bit strange that the temperature doesn't have it's own field similar to depth (but not surprised). I don't believe the information I'm looking for is in the "Comments" section...I've spot checked ~10 species and I think the "comments" field is the actual "Biology" field on the fishbase species page - correct? 

With getEnviroClimateRange() in the previous version, temp was spit out and is probably easier to use regex to extract the information from that output...anyway to bring back that functionality?

![image](https://cloud.githubusercontent.com/assets/6842510/7889812/bd4daabc-05f6-11e5-834b-cfa583a6e895.png)

**Comment by cboettig** [comment]
Good point, the "comments" field is definitely the "biology" section.  Presumably those numbers are buried in the database somewhere, and I'll see if I can track them down.  As you see, the back end database is a bit of a mess and we're trying to come up with a better way to address this problem more generally, so that users don't have this issue of 'where the heck do I find X?'  It will take a bit longer but I think be a better long-term solution then going back to the web scraping approach.  Sorry about this.

**Comment by jebyrnes** [comment]
Amused to find this - and I second interest in it! I even have a use case (looking at shifts in mean assemblage temperature tolerance) that I'm happy to volunteer as an example!

**Comment by rBatt** [comment]
@mpinsky and I would use this type of thing too.

**Comment by cboettig** [comment]
Thanks @jebyrnes @rBatt @jafflerbach for the feedback!  I think this highlights a more general problem that it's really hard to know what table to look in for what piece of data.  I think @sckott and I need to figure out a better way to approach that question, either on the server/API side or the rfishbase package side. 

Currently, you can get a list of tables in the `heartbeat` function, and then you just have to search each of the (likely?) tables for any mention of the term.  We're looking into a better way to do that.

**Comment by cboettig** [comment]
@jebyrnes @rBatt @jafflerbach Found it!

Looks like min max temperature information is reported at the `stock` level rather than the `species` level.  This will make things a bit complicated. For example:

```r
stocks(common_to_sci("trout"), c("TempMin", "TempMax", "StockDefs"))
```

You'll see several hits for the same species since it has different stocks, add `StockCode` and `SpeciesCode` to the fields list to see this.  StockDefs provides a detailed but not very computer-friendly description of how the stocks are defined (e.g. geographic area).  Use `stocks` function with no field to get the whole table, you'll see it has various columns that might be of use to you (among many that are not).  

Let me know if this works or how you might aggregate these to a species level estimate. (e.g. is it reasonable to just take the min of the mins and max of the maxs and call that the species min max?  The answer will probably depend on how you all are using this data!) Whatever fishbase is doing it on those summary pages is not obvious to me.

**Comment by rBatt** [comment]
For my purposes the min of mins and max of maxs would probably work well
for me (but like you say, depends on your use). However, I wouldn't discard
the more detailed level (i.e., still be able to use stocks()), because I
can easily imagine cases where you might want to know region-specific
values.

**Comment by jafflerbach** [comment]
Thanks @cboettig - this is definitely what I was looking for. I do value the stock level information for my work so if there is a way to keep those details while also having a more dedicated function to get the min of mins and max of max's as you suggest, I would find that very useful.

**Comment by cboettig** [comment]
Great.  I'm not sure if we should indeed implement a more specific
function, since having a unique function for most columns in most tables
would quickly get unwieldy.  My temptation is actually to go the other way,
and try and compute more "table joins" on the server side, so the user has
fewer instead of more functions to navigate.  Of course this leaves it up
to the user to subset the tables for the information they need, which could
be a pain.  My intuition is that users would general prefer to subset
tables than to have to join tables, but I'm not sure.  Do let me know if
you have any thoughts on how you'd like to see this handled in general.

On Thu, Jul 2, 2015 at 2:53 PM, Jamie Afflerbach <notifications@github.com>
wrote:

> Thanks @cboettig <https://github.com/cboettig> - this is definitely what
> I was looking for. I do value the stock level information for my work so if
> there is a way to keep those details while also having a more dedicated
> function to get the min of mins and max of max's as you suggest, I would
> find that very useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rfishbase/issues/47#issuecomment-118178614>.
>



-- 
Carl Boettiger
UC Santa Cruz
http://carlboettiger.info/

**Comment by cboettig** [comment]
Closing this since min/max temp is implemented in the `stock` table.  Working on a few other issues to address the bigger problem here as indicated in the cross-links to this issue.
