### ISSUE TITLE
updateCache bug

### ISSUE THREAD

**Issue by tbridge1981** [ropensci/rfishbase#86]
I am trying to update the Cache 'updateCache(”.”)' in rfishbase, but the program keeps crashing. I understand it may take considerable time, but I have left it running for several days and each time R simply times out. Is this a bug with the function or the website?

**Comment by cboettig** [comment]
Sounds like you may be running a very outdated version of `rfishbase`.  Can you try updating to the current version on CRAN? (2.1.0 currently).  Also be sure to see the README and vignette of the current version, since almost all of the functions have changed from that which was described in the original J. Fish Biology publication.  (For instance, there is no longer an `updateCache` function nor any need to do that).  Apologies for these breaking-backwards-compatibility changes, but I hope you find the new version substantially richer and easier to use than the original.  Cheers,
